
name: 'Changelog Releasenotes Action'
description: 'Generate release notes from CHANGELOG.md and upload them into github release description'
author: 'kuvaus'
branding:
  color: "green"
  icon: "file-text"

inputs:
  changelog:
    description: 'The input path of the changelog file. Default: `CHANGELOG.md`'
    required: false
  filtered_changelog:
    description: 'The output path of the release notes file'
    required: false
  changelog_format:
    description: 'Changelog format, keepachangelog or other'
    required: false
  start_token:
    description: 'The start tag of the release notes'
    required: false
  end_token:
    description: 'The end tag of the release notes'
    required: false
  specific_tag:
    description: 'Extract release notes from a specific tag (e.g. v0.1.2) instead of the newest one, default: empty'
    required: false
  skip_n_lines:
    description: 'Skip first N lines in parsing'
    required: false
  upcoming_release:
    description: 'Set this to `true` to get release notes from the [Upcoming] section instead of the first tagged release'
    required: false
  create_release:
    description: 'Set this to `true` to make a new release if one does not exist'
    required: false
  update_release:
    description: 'Set this to `true` to update a release'
    required: false
    
#
# Outputs the release notes in text in here
#

outputs:
  releasenotes:
    description: 'The filtered release notes'

 runs:
   using: node20
   main: dist/index.js


